In [65]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

# Nettoyage du dataset

In [66]:
df = pd.read_csv("houses_Madrid.csv")
df

,Unnamed: 0,id,title,subtitle,sq_mt_built,sq_mt_useful,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,...,energy_certificate,has_parking,has_private_parking,has_public_parking,is_parking_included_in_price,parking_price,is_orientation_north,is_orientation_west,is_orientation_south,is_orientation_east
0,0,21742,"Piso en venta en calle de Godella, 64","San Cristóbal, Madrid",64.0,60.0,2,1.0,NaN,NaN,...,D,False,NaN,NaN,NaN,NaN,False,True,False,False
1,1,21741,Piso en venta en calle de la del Manojo de Rosas,"Los Ángeles, Madrid",70.0,NaN,3,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,21740,"Piso en venta en calle del Talco, 68","San Andrés, Madrid",94.0,54.0,2,2.0,NaN,NaN,...,no indicado,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,21739,Piso en venta en calle Pedro Jiménez,"San Andrés, Madrid",64.0,NaN,2,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,False,False,True,False
4,4,21738,Piso en venta en carretera de Villaverde a Val...,"Los Rosales, Madrid",108.0,90.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21737,21737,5,Ático en venta en Casco Histórico de Barajas,"Barajas, Madrid",78.0,NaN,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21738,21738,4,Piso en venta en Urb. Campo de las Naciones - ...,"Barajas, Madrid",96.0,83.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,False,True,True,True
21739,21739,3,Piso en venta en Campo de las Naciones-Corralejos,"Barajas, Madrid",175.0,NaN,4,2.0,NaN,NaN,...,E,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21740,21740,2,"Chalet adosado en venta en calle Burriana, 12","Campo de las Naciones-Corralejos, Madrid",289.0,NaN,4,3.0,3.0,304.0,...,en trámite,True,NaN,NaN,True,0.0,False,False,True,False
21741,21741,1,"Piso en venta en calle San Epifanio, 9","Imperial, Madrid",72.0,NaN,2,2.0,NaN,NaN,...,A,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN

In [67]:
df.describe()

,Unnamed: 0,id,sq_mt_built,sq_mt_useful,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,latitude,longitude,...,rent_price_by_area,buy_price,buy_price_by_area,built_year,are_pets_allowed,is_furnished,is_kitchen_equipped,has_private_parking,has_public_parking,parking_price
count,21742.000000,21742.000000,21616.000000,8228.000000,21742.000000,21726.000000,1437.000000,1432.000000,0.0,0.0,...,0.0,2.174200e+04,21742.000000,10000.000000,0.0,0.0,0.0,0.0,0.0,7719.000000
mean,10870.500000,10871.500000,146.920892,103.458192,3.005749,2.091687,3.128740,241.692737,NaN,NaN,...,NaN,6.537356e+05,4020.523871,1970.046400,NaN,NaN,NaN,NaN,NaN,2658.000518
std,6276.519112,6276.519112,134.181865,88.259192,1.510497,1.406992,0.907713,247.484853,NaN,NaN,...,NaN,7.820821e+05,1908.418774,69.386705,NaN,NaN,NaN,NaN,NaN,13360.966258
min,0.000000,1.000000,13.000000,1.000000,0.000000,1.000000,1.000000,1.000000,NaN,NaN,...,NaN,3.600000e+04,447.000000,1723.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,5435.250000,5436.250000,70.000000,59.000000,2.000000,1.000000,2.000000,2.000000,NaN,NaN,...,NaN,1.980000e+05,2551.000000,1957.000000,NaN,NaN,NaN,NaN,NaN,0.000000
50%,10870.500000,10871.500000,100.000000,79.000000,3.000000,2.000000,3.000000,232.000000,NaN,NaN,...,NaN,3.750000e+05,3720.000000,1970.000000,NaN,NaN,NaN,NaN,NaN,0.000000
75%,16305.750000,16306.750000,162.000000,113.000000,4.000000,2.000000,4.000000,354.000000,NaN,NaN,...,NaN,7.636000e+05,5000.000000,1994.000000,NaN,NaN,NaN,NaN,NaN,0.000000
max,21741.000000,21742.000000,999.000000,998.000000,24.000000,16.000000,7.000000,997.000000,NaN,NaN,...,NaN,8.800000e+06,18889.000000,8170.000000,NaN,NaN,NaN,NaN,NaN,600000.000000

In [68]:
df.isnull().sum()

Unnamed: 0                          0
id                                  0
title                               0
subtitle                            0
sq_mt_built                       126
sq_mt_useful                    13514
n_rooms                             0
n_bathrooms                        16
n_floors                        20305
sq_mt_allotment                 20310
latitude                        21742
longitude                       21742
raw_address                      5465
is_exact_address_hidden             0
street_name                      5905
street_number                   15442
portal                          21742
floor                            2607
is_floor_under                   1170
door                            21742
neighborhood_id                     0
operation                           0
rent_price                          0
rent_price_by_area              21742
is_rent_price_known                 0
buy_price                           0
buy_price_by_area                   0
is_buy_price_known                  0
house_type_id                     391
is_renewal_needed                   0
is_new_development                992
built_year                      11742
has_central_heating              8134
has_individual_heating           8134
are_pets_allowed                21742
has_ac                          10531
has_fitted_wardrobes             8343
has_lift                         2386
is_exterior                      3043
has_garden                      20186
has_pool                        16571
has_terrace                     12194
has_balcony                     18421
has_storage_room                14044
is_furnished                    21742
is_kitchen_equipped             21742
is_accessible                   17668
has_green_zones                 17685
energy_certificate                  0
has_parking                         0
has_private_parking             21742
has_public_parking              21742
is_parking_included_in_price    14023
parking_price                   14023
is_orientation_north            10384
is_orientation_west             10384
is_orientation_south            10384
is_orientation_east             10384
dtype: int64

In [69]:
df.dtypes

Unnamed: 0                        int64
id                                int64
title                            object
subtitle                         object
sq_mt_built                     float64
sq_mt_useful                    float64
n_rooms                           int64
n_bathrooms                     float64
n_floors                        float64
sq_mt_allotment                 float64
latitude                        float64
longitude                       float64
raw_address                      object
is_exact_address_hidden            bool
street_name                      object
street_number                    object
portal                          float64
floor                            object
is_floor_under                   object
door                            float64
neighborhood_id                  object
operation                        object
rent_price                        int64
rent_price_by_area              float64
is_rent_price_known                bool
buy_price                         int64
buy_price_by_area                 int64
is_buy_price_known                 bool
house_type_id                    object
is_renewal_needed                  bool
is_new_development               object
built_year                      float64
has_central_heating              object
has_individual_heating           object
are_pets_allowed                float64
has_ac                           object
has_fitted_wardrobes             object
has_lift                         object
is_exterior                      object
has_garden                       object
has_pool                         object
has_terrace                      object
has_balcony                      object
has_storage_room                 object
is_furnished                    float64
is_kitchen_equipped             float64
is_accessible                    object
has_green_zones                  object
energy_certificate               object
has_parking                        bool
has_private_parking             float64
has_public_parking              float64
is_parking_included_in_price     object
parking_price                   float64
is_orientation_north             object
is_orientation_west              object
is_orientation_south             object
is_orientation_east              object
dtype: object

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21742 entries, 0 to 21741
Data columns (total 58 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    21742 non-null  int64
 1   id                            21742 non-null  int64
 2   title                         21742 non-null  object
 3   subtitle                      21742 non-null  object
 4   sq_mt_built                   21616 non-null  float64
 5   sq_mt_useful                  8228 non-null   float64
 6   n_rooms                       21742 non-null  int64
 7   n_bathrooms                   21726 non-null  float64
 8   n_floors                      1437 non-null   float64
 9   sq_mt_allotment               1432 non-null   float64
 10  latitude                      0 non-null      float64
 11  longitude                     0 non-null      float64
 12  raw_address                   16277 non-null  object
 13  is_exact_address_hidden       21742 non-null  bool
 14  street_name                   15837 non-null  object
 15  street_number                 6300 non-null   object
 16  portal                        0 non-null      float64
 17  floor                         19135 non-null  object
 18  is_floor_under                20572 non-null  object
 19  door                          0 non-null      float64
 20  neighborhood_id               21742 non-null  object
 21  operation                     21742 non-null  object
 22  rent_price                    21742 non-null  int64
 23  rent_price_by_area            0 non-null      float64
 24  is_rent_price_known           21742 non-null  bool
 25  buy_price                     21742 non-null  int64
 26  buy_price_by_area             21742 non-null  int64
 27  is_buy_price_known            21742 non-null  bool
 28  house_type_id                 21351 non-null  object
 29  is_renewal_needed             21742 non-null  bool
 30  is_new_development            20750 non-null  object
 31  built_year                    10000 non-null  float64
 32  has_central_heating           13608 non-null  object
 33  has_individual_heating        13608 non-null  object
 34  are_pets_allowed              0 non-null      float64
 35  has_ac                        11211 non-null  object
 36  has_fitted_wardrobes          13399 non-null  object
 37  has_lift                      19356 non-null  object
 38  is_exterior                   18699 non-null  object
 39  has_garden                    1556 non-null   object
 40  has_pool                      5171 non-null   object
 41  has_terrace                   9548 non-null   object
 42  has_balcony                   3321 non-null   object
 43  has_storage_room              7698 non-null   object
 44  is_furnished                  0 non-null      float64
 45  is_kitchen_equipped           0 non-null      float64
 46  is_accessible                 4074 non-null   object
 47  has_green_zones               4057 non-null   object
 48  energy_certificate            21742 non-null  object
 49  has_parking                   21742 non-null  bool
 50  has_private_parking           0 non-null      float64
 51  has_public_parking            0 non-null      float64
 52  is_parking_included_in_price  7719 non-null   object
 53  parking_price                 7719 non-null   float64
 54  is_orientation_north          11358 non-null  object
 55  is_orientation_west           11358 non-null  object
 56  is_orientation_south          11358 non-null  object
 57  is_orientation_east           11358 non-null  object
dtypes: bool(5), float64(17), int64(6), object(30)
memory usage: 8.9+ MB

In [71]:
df.drop(["sq_mt_useful", "n_floors", "sq_mt_allotment", "latitude", "longitude", "street_number", "portal", "door", "rent_price_by_area", "built_year", "has_central_heating", "has_individual_heating", "are_pets_allowed", "has_ac", "has_fitted_wardrobes", "has_ac", "has_garden", "has_pool", "has_terrace", "has_balcony", "has_storage_room", "is_furnished", "is_kitchen_equipped", "is_accessible", "has_green_zones", "has_parking", "has_private_parking", "has_public_parking", "is_parking_included_in_price", "parking_price", "is_orientation_north", "is_orientation_west", "is_orientation_south", "is_orientation_east"], axis=1, inplace=True)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21742 entries, 0 to 21741
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               21742 non-null  int64
 1   id                       21742 non-null  int64
 2   title                    21742 non-null  object
 3   subtitle                 21742 non-null  object
 4   sq_mt_built              21616 non-null  float64
 5   n_rooms                  21742 non-null  int64
 6   n_bathrooms              21726 non-null  float64
 7   raw_address              16277 non-null  object
 8   is_exact_address_hidden  21742 non-null  bool
 9   street_name              15837 non-null  object
 10  floor                    19135 non-null  object
 11  is_floor_under           20572 non-null  object
 12  neighborhood_id          21742 non-null  object
 13  operation                21742 non-null  object
 14  rent_price               21742 non-null  int64
 15  is_rent_price_known      21742 non-null  bool
 16  buy_price                21742 non-null  int64
 17  buy_price_by_area        21742 non-null  int64
 18  is_buy_price_known       21742 non-null  bool
 19  house_type_id            21351 non-null  object
 20  is_renewal_needed        21742 non-null  bool
 21  is_new_development       20750 non-null  object
 22  has_lift                 19356 non-null  object
 23  is_exterior              18699 non-null  object
 24  energy_certificate       21742 non-null  object
dtypes: bool(4), float64(2), int64(6), object(13)
memory usage: 3.6+ MB

In [73]:
df.dtypes

Unnamed: 0                   int64
id                           int64
title                       object
subtitle                    object
sq_mt_built                float64
n_rooms                      int64
n_bathrooms                float64
raw_address                 object
is_exact_address_hidden       bool
street_name                 object
floor                       object
is_floor_under              object
neighborhood_id             object
operation                   object
rent_price                   int64
is_rent_price_known           bool
buy_price                    int64
buy_price_by_area            int64
is_buy_price_known            bool
house_type_id               object
is_renewal_needed             bool
is_new_development          object
has_lift                    object
is_exterior                 object
energy_certificate          object
dtype: object

In [74]:
num_cols = df.select_dtypes(include=["float64", "int64"]).columns
cat_cols = df.select_dtypes(include=["object", "category"]).columns

In [75]:
preprocess = ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="mean"), num_cols),
        ("cat", SimpleImputer(strategy="most_frequent"), cat_cols)
    ]
)

In [88]:
preprocess.fit_transform(df).shape

(21742, 21)

In [81]:
[x for x in a if x not in b]

[]

In [82]:
df_imputed = pd.DataFrame(
    preprocess.fit_transform(df),
    columns=list(num_cols) + list(cat_cols) + ["is_exact_address_hidden","is_rent_price_known","is_buy_price_known","is_renewal_needed"]
)

ValueError: Shape of passed values is (21742, 21), indices imply (21742, 25)

In [ ]:
df_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21742 entries, 0 to 21741
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          21742 non-null  object
 1   id                  21742 non-null  object
 2   sq_mt_built         21742 non-null  object
 3   n_rooms             21742 non-null  object
 4   n_bathrooms         21742 non-null  object
 5   rent_price          21742 non-null  object
 6   buy_price           21742 non-null  object
 7   buy_price_by_area   21742 non-null  object
 8   title               21742 non-null  object
 9   subtitle            21742 non-null  object
 10  raw_address         21742 non-null  object
 11  street_name         21742 non-null  object
 12  floor               21742 non-null  object
 13  is_floor_under      21742 non-null  object
 14  neighborhood_id     21742 non-null  object
 15  operation           21742 non-null  object
 16  house_type_id       21742 non-null  object
 17  is_new_development  21742 non-null  object
 18  has_lift            21742 non-null  object
 19  is_exterior         21742 non-null  object
 20  energy_certificate  21742 non-null  object
dtypes: object(21)
memory usage: 3.5+ MB